#!/bin/bash
if [[ $EUID -ne 0 ]]; then
echo -e "\033[1;31m  Este script pode ser executado apenas como root.\033[0m"
exit 1
fi

COLLECTED_DIR="collected_files"
mkdir "$COLLECTED_DIR"

echo -e "\033[1;35m Coletando arquivos do sistema...\033[0m"

echo -e "\033[1;95m Listando informações sobre discos e partições...\033[0m"
lsblk > $COLLECTED_DIR/disk_info.txt

echo -e "\033[1;95m Coletando informações de rede...\033[0m"
ss > $COLLECTED_DIR/active_connections.txt
netstat > $COLLECTED_DIR/open_ports.txt

echo -e "\033[1;95m Coletando lista de processos...\033[0m"
ps aux > $COLLECTED_DIR/process_list.txt

echo -e "\033[1;95m Coletando logs do sistema...\033[0m"
cp /var/log/syslog $COLLECTED_DIR/syslog.log
cp /var/log/auth.log $COLLECTED_DIR/auth.log
cp /var/log/dmesg $COLLECTED_DIR/dmesg.log

echo -e "\033[1;95m Coletando arquivos de configuração...\033[0m"
cp -r /etc $COLLECTED_DIR/config.txt

echo -e "\033[1;95m Listando o diretório raiz...\033[0m"
ls -la / > $COLLECTED_DIR/root_dir_list.txt

tar -czf "TraceHunter_$(hostname)_$(date +%Y%m%d_%H%M%S).tar.gz" $COLLECTED_DIR
